package com.fincore;

import com.fincore.db.DatabaseManager;
import com.fincore.model.AuthUser;
import com.fincore.repository.AuditLogRepository;
import com.fincore.repository.UserRepository;
import com.fincore.repository.impl.JdbcAuditLogRepository;
import com.fincore.repository.impl.JdbcUserRepository;
import com.fincore.service.AuthService;
import com.fincore.service.exception.BankingException;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Integration test verifying Database-backed Authentication (Oracle 10g XE / SQLite).
 */
public class AuthIntegrationTest {

    private static UserRepository userRepo;
    private static AuthService authService;

    @BeforeAll
    static void setup() {
        DatabaseManager db = DatabaseManager.getInstance();
        db.initializeDatabase();
        userRepo = new JdbcUserRepository(db);
        AuditLogRepository auditRepo = new JdbcAuditLogRepository(db);
        authService = new AuthService(userRepo, auditRepo);
    }

    @Test
    @DisplayName("Authenticate default admin seeded user")
    void testDefaultAdminAuthentication() {
        AuthUser user = authService.login("admin", "admin123");
        assertNotNull(user);
        assertEquals("admin", user.getUsername());
        assertEquals("ADMIN", user.getRole());
        assertTrue(authService.isAuthenticated());

        authService.logout();
        assertFalse(authService.isAuthenticated());
        assertNull(authService.getCurrentUser());
    }

    @Test
    @DisplayName("Reject invalid password with BankingException")
    void testInvalidPasswordRejection() {
        assertThrows(BankingException.class, () -> authService.login("admin", "wrongpassword"));
    }

    @Test
    @DisplayName("Reject non-existent username with BankingException")
    void testNonExistentUserRejection() {
        assertThrows(BankingException.class, () -> authService.login("non_existent_user_999", "secret"));
    }

    @Test
    @DisplayName("User CRUD: INSERT, SELECT, UPDATE, DELETE in users table")
    void testUserCrudLifecycle() {
        String uid = UUID.randomUUID().toString().substring(0, 8);
        String username = "testuser_" + uid;

        AuthUser newUser = new AuthUser(username, "pass_" + uid, "Test User " + uid, "USER", "ACTIVE");
        AuthUser saved = userRepo.save(newUser);
        assertNotNull(saved.getId(), "User ID should be generated by DBMS");

        Optional<AuthUser> fetched = userRepo.findById(saved.getId());
        assertTrue(fetched.isPresent());
        assertEquals("Test User " + uid, fetched.get().getFullName());

        // Update
        fetched.get().setFullName("Updated Name " + uid);
        assertTrue(userRepo.update(fetched.get()));

        AuthUser updated = userRepo.findById(saved.getId()).orElseThrow();
        assertEquals("Updated Name " + uid, updated.getFullName());

        // Authenticate new user
        Optional<AuthUser> authResult = userRepo.authenticate(username, "pass_" + uid);
        assertTrue(authResult.isPresent());

        // Delete
        assertTrue(userRepo.deleteById(saved.getId()));
        assertTrue(userRepo.findById(saved.getId()).isEmpty());
    }
}
