package com.fincore;

import com.fincore.db.DatabaseManager;
import com.fincore.model.Budget;
import com.fincore.model.FinancialRecord;
import com.fincore.repository.AccountRepository;
import com.fincore.repository.AuditLogRepository;
import com.fincore.repository.BudgetRepository;
import com.fincore.repository.FinancialRecordRepository;
import com.fincore.repository.TransactionRepository;
import com.fincore.repository.impl.JdbcAccountRepository;
import com.fincore.repository.impl.JdbcAuditLogRepository;
import com.fincore.repository.impl.JdbcBudgetRepository;
import com.fincore.repository.impl.JdbcFinancialRecordRepository;
import com.fincore.repository.impl.JdbcTransactionRepository;
import com.fincore.service.FinanceService;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Integration test for the Complete Financial Record CRUD Module:
 * - INSERT -> add income/expense
 * - SELECT -> query & display records
 * - UPDATE -> edit record
 * - DELETE -> remove record
 * Also tests budget tracking and financial aggregations.
 */
public class FinanceCrudIntegrationTest {

    private static FinancialRecordRepository finRecordRepo;
    private static BudgetRepository budgetRepo;
    private static FinanceService financeService;

    @BeforeAll
    static void setup() {
        DatabaseManager db = DatabaseManager.getInstance();
        db.initializeDatabase();

        finRecordRepo = new JdbcFinancialRecordRepository(db);
        budgetRepo = new JdbcBudgetRepository(db);
        AccountRepository accountRepo = new JdbcAccountRepository(db);
        TransactionRepository txRepo = new JdbcTransactionRepository(db);
        AuditLogRepository auditRepo = new JdbcAuditLogRepository(db);

        financeService = new FinanceService(finRecordRepo, budgetRepo, accountRepo, txRepo, auditRepo);
    }

    @Test
    @DisplayName("Complete CRUD Lifecycle: INSERT -> SELECT -> UPDATE -> DELETE")
    void testCompleteCrudLifecycle() {
        // 1. INSERT (Create)
        FinancialRecord record = new FinancialRecord(
                FinancialRecord.Type.EXPENSE,
                "Office Supplies",
                149.99,
                "CHK-100102",
                "Laser Printer Toner Cartridges",
                LocalDate.of(2026, 9, 20)
        );

        FinancialRecord inserted = finRecordRepo.save(record);
        assertNotNull(inserted.getId(), "Primary Key ID should be auto-generated by DBMS");
        Long recordId = inserted.getId();

        // 2. SELECT (Read)
        Optional<FinancialRecord> fetched = finRecordRepo.findById(recordId);
        assertTrue(fetched.isPresent(), "Record must be findable by ID via SELECT");
        assertEquals("Office Supplies", fetched.get().getCategory());
        assertEquals(149.99, fetched.get().getAmount(), 0.001);
        assertEquals("CHK-100102", fetched.get().getAccountNumber());
        assertEquals("Laser Printer Toner Cartridges", fetched.get().getDescription());

        // 3. UPDATE (Modify)
        FinancialRecord toUpdate = fetched.get();
        toUpdate.setAmount(199.50);
        toUpdate.setDescription("High-Yield Toner & Premium Paper");
        boolean updateResult = finRecordRepo.update(toUpdate);
        assertTrue(updateResult, "UPDATE query should affect 1 row");

        // Verify UPDATE via SELECT
        FinancialRecord verifiedUpdate = finRecordRepo.findById(recordId).orElseThrow();
        assertEquals(199.50, verifiedUpdate.getAmount(), 0.001);
        assertEquals("High-Yield Toner & Premium Paper", verifiedUpdate.getDescription());

        // 4. DELETE (Remove)
        boolean deleteResult = finRecordRepo.deleteById(recordId);
        assertTrue(deleteResult, "DELETE query should affect 1 row");

        // Verify DELETE via SELECT
        Optional<FinancialRecord> afterDelete = finRecordRepo.findById(recordId);
        assertTrue(afterDelete.isEmpty(), "Record should no longer exist after DELETE");
    }

    @Test
    @DisplayName("Aggregations & Metrics: Income, Expenses, and Category Breakdown")
    void testFinancialAggregations() {
        double income = financeService.getTotalIncome();
        double expenses = financeService.getTotalExpenses();
        assertTrue(income > 0, "Seeded income should be positive");
        assertTrue(expenses > 0, "Seeded expenses should be positive");

        Map<String, Double> expenseBreakdown = financeService.getCategoryBreakdown(FinancialRecord.Type.EXPENSE);
        assertNotNull(expenseBreakdown);
        assertFalse(expenseBreakdown.isEmpty());
    }

    @Test
    @DisplayName("Relational Join: Budget tracking calculates expenditures from financial_records")
    void testBudgetWithSpendingJoin() {
        List<Budget> budgets = financeService.getAllBudgetsWithSpending();
        assertNotNull(budgets);
        assertFalse(budgets.isEmpty(), "Seeded budgets should exist");

        for (Budget b : budgets) {
            assertNotNull(b.getCategory());
            assertTrue(b.getMonthlyLimit() > 0);
            assertTrue(b.getSpentAmount() >= 0);
            assertEquals(b.getMonthlyLimit() - b.getSpentAmount(), b.getRemainingAmount(), 0.01);
        }
    }
}
